#!/usr/bin/env bash
set -uo pipefail

out="submissions/draft-report-index.md"

status_line() {
  path="$1"
  label="$2"
  content="$3"
  if [ -e "$path" ]; then
    echo "| ${label} | \`${path}\` | exists | ${content} |"
  else
    echo "| ${label} | \`${path}\` | missing | ${content} |"
  fi
}

baseline_record_status() {
  path="external/xv6-baseline-record.md"
  if [ -e "$path" ]; then
    echo "| xv6 baseline metadata | \`${path}\` | exists | metadata generated; records make success and boot evidence; manual interaction TODO |"
  else
    echo "| xv6 baseline metadata | \`${path}\` | missing | TODO: run \`bash scripts/xv6/fetch-xv6.sh --run\` after authorization |"
  fi
}

mkdir -p submissions

{
  echo "# Initial Submission Material Index Draft"
  echo
  echo "Generated time: TODO: fill manually before final submission"
  echo
  echo "This file is generated or updated by \`scripts/collect-report.sh\`."
  echo "It is not the final technical report, does not generate PDF, and does not include registration materials, private data, or fabricated results."
  echo
  echo "## Material Index"
  echo
  echo "| Material | Path | File | Content status |"
  echo "| --- | --- | --- | --- |"
  status_line "README.md" "Project homepage" "stage19 student-first front door: first-time orientation, prerequisite knowledge list, six curated readings (full pool in references/), learning path, labctl quick run, teacher section, judge entry moved lower with Baidu asset link, directory tour, honest evidence status and real-pothole closing note"
  status_line "docs/README.md" "Documentation guide" "stage19 reader routing: first-time learners (now incl. references reading list), lab runners, teachers/TAs, judges (incl. submission checklist), and historical process records (lowest priority for newcomers)"
  status_line "docs/teacher_guide.md" "teacher guide" "stage12: 2/3/5-session course plans, mandatory vs optional labs, acceptance via teammate-verify summary blocks, anti-fabrication spot checks, student environment handling"
  status_line "docs/grading_and_rubric.md" "grading and rubric" "stage12: four grading dimensions, per-lab focus, unified deduction table (hardcoded outputs = fabrication), bonus items, grade bands"
  status_line "docs/troubleshooting.md" "troubleshooting" "stage12: symptom/cause/fix/what-to-report for WSL, PATH, /mnt slowness, Ctrl+Z + cleanup-qemu, git apply order, usys.pl filemode warning, RWX warning, DIRSIZ, timeout semantics"
  status_line "docs/00_project_plan.md" "Project plan" "MVP draft"
  status_line "docs/01_requirement_analysis.md" "Requirement and scoring analysis" "MVP draft"
  status_line "docs/02_lab_design.md" "Lab system design" "MVP draft"
  status_line "docs/03_step_by_step_guide.md" "Step-by-step guide outline" "outline draft"
  status_line "docs/04_test_report.md" "Test report" "includes real baseline make, hardened boot evidence retry, lab1/lab2/lab3/lab4 outputs, integrated 0001-0007 evidence, and lab2 v0.2 outputs"
  status_line "docs/05_ai_usage_record.md" "AI usage record" "active record"
  status_line "docs/06_progress_log.md" "Progress log" "active record"
  status_line "docs/07_faq_and_issues.md" "FAQ and issue record" "template"
  status_line "docs/08_reference_and_license.md" "Reference and license record" "active record"
  status_line "docs/09_github_workflow.md" "GitHub workflow" "workflow draft"
  status_line "docs/10_red_team_review.md" "Internal red-team review" "draft"
  status_line "docs/11_xv6_baseline_plan.md" "xv6 baseline plan" "stage1b plan"
  status_line "docs/12_lab1_patch_review.md" "lab1 patch reproducibility review" "stage2b red-team; clean-baseline apply/make/hello verified"
  status_line "docs/14_lab1_argint_extension_review.md" "lab1 argint extension review" "stage3b red-team: 0001+0002 reproduced (make/hello/add2); add2 call chain, argint mechanism, teaching-value assessment"
  status_line "docs/15_lab2_process_observation_review.md" "lab2 process observation review" "stage4b red-team: clean-baseline apply/make/pstatetest verified; teaching limits + lab1/lab2 conflict measured"
  status_line "docs/16_patch_strategy_and_integration_plan.md" "patch strategy and integration plan" "stage4b conflict measured; stage4c integrated-labs sequence built and verified"
  status_line "docs/17_integrated_labs_review.md" "integrated-labs review" "stage4d red-team plus stage6a update: 0001-0005 reproduced; hello/add2test/pstatetest/pcounttest/pchildtest/fcounttest in one build"
  status_line "docs/18_integrated_helper_review.md" "integrated apply helper safety review" "stage4f red-team plus stage6a update: preview safe; --run/--make always require --yes; --make --yes applies 0001-0005"
  status_line "docs/19_lab2_v0.2_process_observation_review.md" "lab2 v0.2 process observation review" "stage5a + stage5b red-team: pcount/pcounttest/pchildtest and negative input; integrated 0001-0004 re-reproduced from clean baseline; 0004 patch unchanged; lock/snapshot analysis and benign usys.pl mode warning documented"
  status_line "docs/20_lab4_file_table_observation_review.md" "lab4 file table observation review" "stage6a + stage6b red-team: fcount/fcounttest; independent lab4 patch and integrated 0005 re-reproduced from clean baseline; both patches unchanged; filecount lock/deadlock/no-leak analysis; sys_fcount in sysfile.c; open/close +1/-1 delta; fcount numbers non-fixed"
  status_line "docs/21_submission_readiness_review.md" "submission readiness review" "stage6d historical snapshot: full integrated 0001-0005 reproduced at that time; superseded by final e8e2fb9 integrated 0001-0007 evidence manifest"
  status_line "docs/22_teammate_reproduction_troubleshooting.md" "teammate reproduction troubleshooting" "stage7a0: explains apply/make completion, boot normal duration, Ctrl+Z risk, qemu/make cleanup, continuation steps, feedback format, and no-log/no-secret boundaries"
  status_line "docs/23_teammate_quickstart.md" "teammate quickstart" "stage7a2: official teammate testing entry; --full first run, --quick retest after make, local-verify before recording, cleanup-qemu after stuck/Ctrl+Z, summary feedback, no external/logs/secrets"
  status_line "docs/24_lab3_lab5_completion_plan.md" "lab3/lab5 completion plan" "stage9c process record with stage11b banner: described 0001-0007 state is historical; current integrated suite is 0001-0009; e8e2fb9 evidence is a historical stable checkpoint recorded elsewhere"
  status_line "docs/final/00_project_overview.md" "final project overview" "stage11b status: OUC xv6 Lab Kit positioning, scoring weights, integrated 0001-0009 (memstat 0008/fdinfo 0009), e8e2fb9 0001-0007 PASS historical, new evidence TBD, evidence boundaries"
  status_line "docs/final/01_environment_setup.md" "final environment setup" "stage8a formal environment and repository hygiene guide"
  status_line "docs/final/02_lab0_baseline_build_boot.md" "final lab0 guide" "stage8a formal lab0 baseline/build/boot guide"
  status_line "docs/final/03_lab1_hello_add2.md" "final lab1 guide" "stage8a formal hello/add2 syscall lab guide"
  status_line "docs/final/04_lab2_process_observation.md" "final lab2 guide" "stage8a formal pstate/pcount/pchild process observation lab guide"
  status_line "docs/final/04b_lab3_page_table_observation.md" "final lab3 guide" "stage9c formal pgcount page-table observation guide; stage11b advanced memstat section now covers independent + integrated 0008"
  status_line "docs/final/05_lab4_file_table_observation.md" "final lab4 guide" "stage9c formal fcount/fdcount file table and fd table observation lab guide; stage11b advanced fdinfo section now covers independent + integrated 0009"
  status_line "docs/final/06_testing_and_verification.md" "final testing and verification" "stage11b testing coverage table now includes memstat/fdinfo; e8e2fb9 0001-0007 lead/root/z2996 full PASS historical; new 0001-0009 teammate verify TBD; real-result boundaries"
  status_line "docs/final/07_teammate_reproduction_guide.md" "final teammate reproduction guide" "stage11b updated teammate reproduction and feedback guide: e8e2fb9 root/z2996 PASS recorded as historical 0001-0007 stable checkpoint; 0001-0009 (with memstattest/fdinfotest) teammate re-verify TBD"
  status_line "docs/final/08_design_decisions_and_tradeoffs.md" "final design decisions" "stage8a formal design tradeoffs and scope control"
  status_line "docs/final/09_ai_usage_and_contribution_statement.md" "final AI usage statement" "stage8a formal AI usage and contribution statement"
  status_line "docs/final/10_reference_and_license_statement.md" "final reference and license statement" "stage8a formal xv6 MIT license boundary and reference-project notes"
  status_line "docs/final/11_known_limits_and_future_work.md" "final limits and future work" "stage11b limits: pgcount/fdcount/memstat/fdinfo observation-only scope boundaries, integrated suite 0001-0009, e8e2fb9 evidence historical, new evidence/platform/privacy/reference items still pending"
  status_line "docs/final/technical_report_v1.0.md" "technical report v1.0" "stage11b judge-facing technical report draft: positioning, labs, integrated 0001-0009 (memstat 0008/fdinfo 0009), e8e2fb9 0001-0007 evidence historical, new evidence TBD, teaching value, license/AI/limits"
  status_line "submissions/submission_checklist.md" "submission checklist" "stage16 submission checklist: current final db85947/0001-0009 three-way PASS + new video recorded; Baidu external-asset row added; video/screenshot privacy review confirmed OK; remaining items include platform method and final rehearsal"
  status_line "submissions/demo_record.md" "demo video record" "stage16: current final 0001-0009 video metadata recorded with duration/resolution/fps/size/SHA256 (20260611 demo, db85947); old 0001-0007 video is historical stable checkpoint; 3 earlier videos are historical; no video files in Git"
  status_line "submissions/teammate_reproduction_record.md" "teammate reproduction record" "stage14: current final db85947/0001-0009 three-way full PASS recorded with summary/screenshot SHA256 and grade-summaries 3/3 clean; e8e2fb9 and 1ba9db6 records historical; raw files not committed"
  status_line "submissions/evidence_manifest.md" "final evidence manifest" "stage16 central index: current final db85947/0001-0009 with three-way full PASS, grade-summaries 3/3 clean, final video metadata + SHA256, 14/14 hash verification, External Asset Package link, e8e2fb9 0001-0007 historical stable checkpoint, and non-committed evidence policy"
  status_line "docs/13_technical_report_v0.1.md" "Technical report v0.1" "historical stage2c draft with stage8b obsolete notice; not final report"
  status_line "reproducibility/README.md" "Reproducibility package" "lab0/lab1/lab2/integrated-labs reproduction checklist and template"
  status_line "labs/lab0-env-setup/README.md" "lab0 environment guide" "xv6 baseline make succeeded; boot evidence found; manual interaction TODO"
  status_line "labs/lab1-system-call/README.md" "lab1 syscall lab" "stage12 tutorial-style: hello minimal and add2 argint, 7-file checklist, call path, hands-on pointer to student tasks"
  status_line "labs/lab1-system-call/student_tasks.md" "lab1 student tasks" "stage12 assignment sheet: reproduce, build your own integer syscall, break-and-fix experiment, rubric and deduction list"
  status_line "labs/lab2-process-and-scheduling/README.md" "lab2 process state observation" "stage12 tutorial-style: pstate/pcount/pchildtest, proc table and lock discipline, scheduling nondeterminism"
  status_line "labs/lab2-process-and-scheduling/student_tasks.md" "lab2 student tasks" "stage12 assignment sheet: lock path audit, new observation syscall, repeated-run timing observation, rubric"
  status_line "labs/lab3-memory-and-pagetable/README.md" "lab3 memory and pagetable" "stage12 tutorial-style: pgcount int observation vs memstat struct-copyout observation; eager/lazy delta experiment; integrated 0006/0008"
  status_line "labs/lab3-memory-and-pagetable/student_tasks.md" "lab3 student tasks" "stage12 assignment sheet: predict-then-verify lazy deltas, copyout data-flow walkthrough, add a struct field with padding analysis, rubric"
  status_line "labs/lab4-file-system/README.md" "lab4 file system" "stage12 tutorial-style: fcount global trend / fdcount per-process / fdinfo single-fd struct view; open-dup-close contrast; not a complete file system lab"
  status_line "labs/lab4-file-system/student_tasks.md" "lab4 student tasks" "stage12 assignment sheet: predict-verify dup effects, fdinfo validation audit, ref observation, negative cases, rubric"
  status_line "labs/lab5-final-integration/README.md" "lab5 final integration" "stage12 tutorial-style capstone for integrated 0001-0009; reproducibility and evidence discipline; no new kernel mechanism"
  status_line "labs/lab5-final-integration/student_tasks.md" "lab5 student tasks" "stage12 assignment sheet: full-suite reproduction with summary block, patch walkthrough incl. 0008/0009, fault log, evidence boundary statement, rubric"
  status_line "tests/lab1/README.md" "lab1 test record" "records patched make and hello output evidence"
  status_line "tests/lab2/README.md" "lab2 test record" "records pstatetest, pcounttest, and pchildtest output evidence"
  status_line "tests/lab3/README.md" "lab3 test record" "records pgcount eager/lazy output captures from independent and integrated 0006; final teammate coverage recorded in submissions evidence manifest"
  status_line "tests/lab4/README.md" "lab4 test record" "records fcounttest/fdcounttest captures and non-fixed count boundary"
  status_line "scripts/xv6/fetch-xv6.sh" "xv6 fetch script" "stage1b tooling"
  status_line "scripts/xv6/check-xv6-baseline.sh" "xv6 baseline check script" "stage1b tooling; make not run by default"
  status_line "scripts/xv6/boot-xv6.sh" "xv6 boot evidence script" "captures boot keywords under soft+hard timeout; default 45s soft, max(timeout+15,75)s hard, 2 attempts, per-attempt logs, trap cleanup"
  status_line "scripts/xv6/run-xv6-command.sh" "xv6 command evidence script" "captures user program output under soft+hard timeout; default 60s soft, max(timeout+15,75)s hard, 2 attempts, fs.img prebuild, trap cleanup, fast QEMU exit on expected output match (stage7a3)"
  status_line "scripts/xv6/apply-lab1-patch.sh" "lab1 patch apply helper" "preview by default; --run resets clean baseline and applies; --make optional"
  status_line "scripts/xv6/apply-integrated-labs.sh" "integrated labs apply helper" "preview by default; --run/--make always require --yes; applies integrated 0001-0009; make has XV6_MAKE_TIMEOUT_SECONDS; make logs ignored"
  status_line "scripts/xv6/doctor.sh" "xv6 doctor script" "stage7a2 read-only environment diagnosis: time/cwd/uname/commit, Git repo, tools, baseline files, logs ignored, QEMU leftovers, /mnt warning; no make or QEMU run"
  status_line "scripts/xv6/cleanup-qemu.sh" "xv6 QEMU cleanup helper" "stage7a2 rescue tool: explains Ctrl+C interrupt vs Ctrl+Z suspend, lists qemu/make qemu processes before/after, warns pkill may affect same-WSL QEMU, exits 0"
  status_line "scripts/xv6/teammate-verify.sh" "teammate one-shot verification" "stage11b workflow: --full clean apply+make and --quick retest; doctor/check-env/baseline, boot, hello/add2/pstate/pcount/pchild/fcount/pgcount/fdcount/memstat/fdinfo verification, copy-to-lead summary in ignored logs"
  status_line "scripts/xv6/local-verify.sh" "local pre-recording verification" "stage7a2 team-lead wrapper around teammate-verify; --full/--quick; recommended --quick before recording"
  status_line "scripts/labctl.sh" "course command entry" "stage13 unified dispatcher: doctor/setup/boot/test/verify/quick/precheck/clean/grade/consistency/hygiene/evidence/report subcommands delegate to existing scripts; adds the lab-to-test matrix (test lab1..lab4/all, list)"
  status_line "scripts/grade-summaries.sh" "TA summary batch parser" "stage13 acceptance aid (not a grader): parses teammate-verify summary blocks into one row per file; flags overall/item inconsistency, missing memstattest-fdinfotest (old suite), duplicate content, commit mismatch; exit 1 when attention needed"
  status_line "scripts/check-docs-consistency.sh" "docs/state consistency gate" "stage13 drift gate: PATCHES list vs patch files, SYS numbers 22-30 in patches, teammate-verify and labctl matrix coverage, stale wording scan outside changelogs, course file presence, report-index freshness"
  status_line "scripts/check-final-hygiene.sh" "final hygiene gate" "stage12 read-only pre-submission gate: external/logs/.claude/.vscode/media-office tracking checks with single PPTX whitelist plus git diff --check"
  status_line "scripts/check-evidence-sha256.sh" "external evidence SHA256 check" "stage14: hashes both evidence sets in place against recorded SHA256 (historical e8e2fb9/0001-0007 plus current final db85947/0001-0009: video, 3 summaries, 2 screenshots); skips when evidence dir absent; latest real run 14/14 matched"
  status_line "patches/lab1-system-call/0001-add-hello-syscall.patch" "lab1 hello syscall patch" "tracked patch; third-party source not submitted"
  status_line "patches/lab1-system-call/0002-add-argint-add2-syscall.patch" "lab1 add2 argint syscall patch" "commit-ready incremental patch after 0001"
  status_line "patches/lab1-system-call/README.md" "lab1 patch guide" "apply/build/run instructions"
  status_line "patches/lab2-process-observation/0001-add-pstate-syscall.patch" "lab2 pstate syscall patch" "commit-ready independent patch from clean baseline"
  status_line "patches/lab2-process-observation/README.md" "lab2 patch guide" "apply/build/run instructions"
  status_line "patches/lab3-memory-and-pagetable/0001-add-pgcount-syscall.patch" "lab3 pgcount syscall patch" "stage9b independent patch from clean baseline; SYS_pgcount 22; eager/lazy pgcounttest verified"
  status_line "patches/lab3-memory-and-pagetable/0002-add-memstat-syscall.patch" "lab3 memstat advanced optional patch" "stage11a independent advanced patch; memstat(struct memstat*) via argaddr+copyout; SYS_memstat 22; clean-baseline round-trip verified; stage11b also integrates this as integrated 0008 (SYS_memstat 29); independent variant not teammate-verified; does not affect historical e8e2fb9"
  status_line "patches/lab3-memory-and-pagetable/README.md" "lab3 patch guide" "apply/build/run instructions and eager/lazy allocation teaching notes"
  status_line "patches/lab4-file-table-observation/0001-add-fcount-syscall.patch" "lab4 fcount syscall patch" "commit-ready independent patch from clean baseline"
  status_line "patches/lab4-file-table-observation/0002-add-fdinfo-syscall.patch" "lab4 fdinfo advanced optional patch" "stage11a independent advanced patch; fdinfo(int,struct fdinfo*) via argint+argaddr+copyout; SYS_fdinfo 22; self-only ofile[fd]; clean-baseline round-trip verified; stage11b also integrates this as integrated 0009 (SYS_fdinfo 30); independent variant not teammate-verified; does not affect historical e8e2fb9"
  status_line "patches/lab4-file-table-observation/README.md" "lab4 patch guide" "apply/build/run instructions"
  status_line "patches/integrated-labs/0001-add-hello-syscall.patch" "integrated hello syscall patch" "comprehensive demo sequence step 1"
  status_line "patches/integrated-labs/0002-add-argint-add2-syscall.patch" "integrated add2 argint syscall patch" "comprehensive demo sequence step 2"
  status_line "patches/integrated-labs/0003-add-pstate-syscall.patch" "integrated pstate syscall patch" "comprehensive demo sequence step 3; uses SYS_pstate 24"
  status_line "patches/integrated-labs/0004-extend-process-observation.patch" "integrated lab2 v0.2 process observation patch" "comprehensive demo sequence step 4; adds SYS_pcount 25, pcounttest, pchildtest"
  status_line "patches/integrated-labs/0005-add-file-table-observation.patch" "integrated lab4 file table observation patch" "comprehensive demo sequence step 5; adds SYS_fcount 26 and fcounttest"
  status_line "patches/integrated-labs/0006-add-pgcount-page-table-observation.patch" "integrated lab3 pgcount patch" "comprehensive demo sequence step 6; adds SYS_pgcount 27 and pgcounttest"
  status_line "patches/integrated-labs/0007-add-fdcount-observation.patch" "integrated lab4 fdcount patch" "comprehensive demo sequence step 7; adds SYS_fdcount 28 and fdcounttest"
  status_line "patches/integrated-labs/0008-add-memstat-copyout-observation.patch" "integrated lab3 memstat patch" "stage11b comprehensive demo sequence step 8; adds SYS_memstat 29 and memstattest; argaddr+copyout+struct ABI; reuses uvmpagecount; address-space observation only, not full memory management"
  status_line "patches/integrated-labs/0009-add-fdinfo-copyout-observation.patch" "integrated lab4 fdinfo patch" "stage11b comprehensive demo sequence step 9; adds SYS_fdinfo 30 and fdinfotest; argint+argaddr+copyout+struct ABI; self-only ofile[fd]; fd metadata observation only, not full file system"
  status_line "patches/integrated-labs/README.md" "integrated patch guide" "stage11b apply/build/run instructions for combined lab1+lab2+lab3+lab4 demo: sequence 0001-0009 incl. memstat 0008 and fdinfo 0009; old 0001-0007 teammate evidence marked historical; 0001-0009 teammate verify TBD"
  status_line "external/README.md" "external directory guide" "baseline management notes"
  baseline_record_status
  status_line "logs/README.md" "logs directory guide" "raw logs ignored by default; current make log is not tracked"
  status_line "references/README.md" "reference reading list" "stage19 layered reading guide: contest pages, official xv6/MIT entries, rCore/uCore/PKE course ecosystems, past winning docs; every link annotated with purpose, when-to-read, and not-an-implementation-source boundary; unverified personal pages clearly flagged"
  status_line "slides/README.md" "PPT directory guide" "stage16 guide for final PPT source, outline, generator, PPTX sync policy, and no-media boundary"
  status_line "slides/final_ppt_outline.md" "final PPT outline" "stage16 16-slide high-impact defense outline: lab kit story, current db85947/0001-0009 facts, evidence cards, tooling map, comparison, and honest boundaries"
  status_line "slides/final_ppt.md" "final PPT source" "stage16 16-slide final defense source: core story (course lab kit, not just syscalls), current final db85947/0001-0009 three-way PASS, 00:03:12 final video, 14/14 evidence hash, Baidu asset package, teaching value, honest boundaries"
  status_line "slides/generate_final_ppt.ps1" "final PPT generator" "stage16 PowerPoint COM generator; reads slides/final_ppt.md and writes a self-drawn deep-blue/cyan 16:9 deck without embedded media"
  status_line "slides/final_defense_ppt.pptx" "final PPTX" "stage16 generated defense deck; 16 slides, 16 speaker notes, self-drawn shapes, no embedded video/screenshot media"
  status_line "videos/README.md" "Demo video notes" "records video policy and no-video-in-Git boundary"
  status_line "videos/demo_script.md" "Demo script draft" "historical 2-3 minute demo flow; final recorded video metadata is tracked in submissions/demo_record.md"
  echo "| Final submission | \`submissions/\` | - | TODO: organize against official requirements |"
  echo
  echo "## Notes"
  echo
  echo "- File existence is checked by this script; content quality still needs human review."
  echo "- \`external/xv6-riscv/\` is intentionally not listed as a tracked submission artifact."
  echo "- xv6 baseline make, hardened boot evidence retry, lab1 patched make, hello output, add2 output, pstatetest output, pcounttest output, pchildtest output, fcounttest output, and integrated sequence evidence are summarized in docs/04_test_report.md."
  echo "- lab1 now has two patch levels: 0001 hello minimal syscall and 0002 add2 argint extension."
  echo "- lab2 has an independent pstate process observation patch from clean baseline."
  echo "- lab3 has an independent pgcount patch, integrated 0006 pgcount, and an independent memstat patch also integrated as 0008; e8e2fb9 0001-0007 full verification by lead/root/z2996 is a historical stable checkpoint in submissions/evidence_manifest.md, and current db85947 0001-0009 has lead/root/z2996 full PASS recorded as final evidence."
  echo "- integrated-labs provides the verified comprehensive demo sequence with hello=22, add2=23, pstate=24, pcount=25, fcount=26, pgcount=27, fdcount=28, memstat=29, fdinfo=30."
  echo "- The child-state demo command is pchildtest; the longer pstatechildtest name is not used because xv6 DIRSIZ caused a real mkfs failure."
  echo "- scripts/xv6/apply-integrated-labs.sh is the recommended helper for final integrated demo reproduction and now applies integrated 0001-0009."
  echo "- scripts/xv6/doctor.sh is the read-only environment diagnosis entry and does not run make/QEMU."
  echo "- scripts/xv6/teammate-verify.sh --full is the recommended first teammate workflow; --quick is for retesting after make already succeeded."
  echo "- scripts/xv6/local-verify.sh --quick is recommended for team-lead pre-recording checks."
  echo "- scripts/xv6/cleanup-qemu.sh is the rescue command when QEMU is stuck or Ctrl+Z suspended a job."
  echo "- stage12 reorganized the repo learner-first: README and docs/README route students/teachers/judges separately; every lab has a tutorial README plus a student_tasks.md assignment sheet; teacher_guide/grading_and_rubric/troubleshooting support running this as a course; submission evidence stays rigorous under submissions/ and docs/final/."
  echo "- scripts/check-final-hygiene.sh and scripts/check-evidence-sha256.sh are the pre-submission gates; evidence hashes are verified in place outside Git; current final db85947 evidence has a recorded 14/14 SHA256 match."
  echo "- stage13 added scripts/labctl.sh (single course entry + per-lab test matrix), scripts/grade-summaries.sh (TA batch acceptance aid, not a grader), and scripts/check-docs-consistency.sh (mechanical drift gate); all three delegate to or check existing assets instead of reimplementing verification."
  echo "- docs/final/ is the formal submission documentation portal for stage8a and should be the basis for technical report v1.0 and PPT."
  echo "- docs/README.md explains the boundary between formal docs/final documentation and historical process records."
  echo "- Technical report v1.0 draft is docs/final/technical_report_v1.0.md; technical report v0.1 is historical only."
  echo "- Final PPT source is slides/final_ppt.md and current PPTX output is slides/final_defense_ppt.pptx; stage16 rebuilt the deck with high-impact visual design using slides/generate_final_ppt.ps1; final human review and rehearsal are still required."
  echo "- docs/13_technical_report_v0.1.md is explicitly marked as a historical draft superseded by docs/final and a future technical report v1.0."
  echo "- Raw logs remain ignored by Git; do not submit logs/*.log."
  echo "- boot-xv6.sh now defaults to 45s soft timeout, hard timeout max(timeout+15,75), and 2 attempts; QEMU long-running stability and manual interactive shell testing remain TODO."
  echo "- run-xv6-command.sh now defaults to 60s soft timeout, hard timeout max(timeout+15,75), and 2 attempts; success is still based only on real log matching."
  echo "- apply-integrated-labs.sh --make --yes uses XV6_MAKE_TIMEOUT_SECONDS, default 600 seconds; make success is never fabricated."
  echo "- Teammate QEMU cleanup troubleshooting is documented in docs/22_teammate_reproduction_troubleshooting.md."
  echo "- Plain-language teammate quickstart is documented in docs/23_teammate_quickstart.md; teammates should copy the COPY THIS SUMMARY TO TEAM LEAD block to the team lead."
  echo "- Video files are not committed; final and historical video metadata plus SHA256 are recorded in submissions/demo_record.md."
  echo "- e8e2fb9 lead/root/z2996 full PASS (integrated 0001-0007) is recorded as a historical stable checkpoint in submissions/teammate_reproduction_record.md; current final db85947/0001-0009 lead/root/z2996 full PASS is recorded as final evidence; old 1ba9db6 records remain historical evidence only."
  echo "- submissions/evidence_manifest.md is the central final evidence index and does not store raw evidence files."
} > "$out"

echo "[OK] report index updated: ${out}"
echo "No PDF or final report was generated."
